#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Zhilian (智联招聘) Job Detail Scraper

Scrapes detailed job information (job description, skill tags, headcount)
from individual job posting URLs collected by the listing spider.

Features:
- Reads job URLs from CSV files generated by zhilian_job_spider.py
- Extracts: headcount, skill tags, full job description
- Progress persistence for resumable scraping
- Saves enriched data to new CSV files
"""

import os
import re
import time
import pandas as pd
import glob
import pickle
import logging
from typing import List, Tuple
from tqdm import tqdm
from colorama import Fore, Style
from pathlib import Path

from selenium.webdriver import Chrome
from selenium.webdriver.common.by import By
from selenium.webdriver import ChromeOptions
from lxml import etree


class JobDetailScraper:
    """Scraper for individual job detail pages on Zhilian."""

    def __init__(self, log_dir: str, progress_dir: str):
        """Initialize the scraper with Chrome WebDriver."""
        self.chrome = self._init_chrome_driver()
        self.pbar = None
        self.log_dir = log_dir
        self.progress_dir = progress_dir
        self.keyword = ''

    def setup_logging(self):
        """Configure file-based logging."""
        log_file = os.path.join(self.log_dir, f'ZL_DL_{time.strftime("%Y%m%d")}.log')
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - %(levelname)s - %(message)s',
            handlers=[logging.FileHandler(log_file, encoding='utf-8')],
        )

    def save_progress(self, completed_urls: List[str]):
        """Save scraping progress for resumability."""
        progress_file = os.path.join(self.progress_dir, f'ZL_DP_{self.keyword}.pkl')
        with open(progress_file, 'wb') as f:
            pickle.dump(completed_urls, f)

    def load_progress(self) -> List[str]:
        """Load previously saved scraping progress."""
        progress_file = os.path.join(self.progress_dir, f'ZL_DP_{self.keyword}.pkl')
        if os.path.exists(progress_file):
            with open(progress_file, 'rb') as f:
                return pickle.load(f)
        return []

    def _init_chrome_driver(self) -> Chrome:
        """Initialize Chrome browser with anti-detection settings."""
        option = ChromeOptions()
        option.add_experimental_option('excludeSwitches', ['enable-automation', 'enable-logging'])
        option.add_argument("--disable-blink-features=AutomationControlled")
        option.add_argument('--log-level=3')
        option.add_argument('--silent')
        option.add_argument('--disable-gpu')
        option.add_argument('--disable-extensions')
        option.add_argument('--disable-default-apps')
        option.add_argument('--disable-notifications')
        return Chrome(options=option)

    def _parse(self, html: str) -> Tuple[str, str, str]:
        """
        Parse job detail page HTML to extract structured information.

        Returns:
            Tuple of (headcount, skill_tags, job_description)
        """
        root = etree.HTML(html)

        # Extract headcount (e.g., "招3人" -> "3")
        recruiting_numbers = root.xpath('//*[@class="summary-plane__info"]/li[last()]/text()')
        str_recruiting_numbers = ''.join(recruiting_numbers)
        str_recruiting_numbers = ''.join(re.compile(r'\d*').findall(str_recruiting_numbers))

        # Extract skill tags
        skill_labels = root.xpath('//*[@class="describtion__skills-content"]//text()')
        str_skill_labels = '/'.join(skill_labels)

        # Extract full job description
        detail_content = root.xpath('//*[@class="describtion__detail-content"]//text()')
        str_detail_content = ''.join(detail_content)

        return (str_recruiting_numbers, str_skill_labels, str_detail_content)

    def log_info(self, message: str):
        """Log an info message to both file and console."""
        logging.info(message)
        print(f"{Fore.GREEN}[INFO] {message}{Style.RESET_ALL}")

    def log_error(self, message: str):
        """Log an error message to both file and console."""
        logging.error(message)
        print(f"{Fore.RED}[ERROR] {message}{Style.RESET_ALL}")

    def update_progress(self):
        """Update the tqdm progress bar."""
        if self.pbar:
            self.pbar.update(1)

    def _read_file(self, filename: str) -> None:
        """
        Read a CSV file containing job URLs and scrape each detail page.

        Args:
            filename: Path to CSV file with job listing URLs
        """
        self.log_info(f"Reading file: {filename}")
        try:
            df = pd.read_csv(filename)
            detail_htmls = df['detail_url']
        except Exception as e:
            self.log_error(f"File read failed: {str(e)}")
            return

        self.keyword = os.path.basename(filename).split('_')[-1].replace('.csv', '')
        completed_urls = self.load_progress()
        completed_set = set(completed_urls)

        # Build output file path
        date = filename.split('_')[1]
        save_path = os.path.join(SAVE_DIR, f'ZL_D_{date}_{self.keyword}.csv')

        if os.path.exists(save_path):
            self.log_info("File already exists, skipping.")
            return

        # Initialize result columns
        df['headcount'] = ''
        df['skill_tags'] = ''
        df['job_description'] = ''

        self.log_info(f"Processing keyword: {self.keyword}")
        self.pbar = tqdm(total=len(detail_htmls), ncols=100, colour='green')

        for index, html in enumerate(detail_htmls):
            if html in completed_set:
                self.update_progress()
                continue

            try:
                self.chrome.get(html)
                headcount, skill_tags, description = self._parse(self.chrome.page_source)

                df.at[index, 'headcount'] = headcount
                df.at[index, 'skill_tags'] = skill_tags
                df.at[index, 'job_description'] = description

                self.update_progress()
            except Exception as e:
                self.log_error(f"Error processing URL {html}: {str(e)}")

        df.to_csv(save_path, index=False, encoding="utf_8_sig")
        self.log_info("File saved successfully.")

    def process_files(self) -> None:
        """Process all CSV files in the data directory."""
        files = glob.glob(os.path.join(DATA_DIR, "*.csv"))
        files.sort()
        for file in files:
            self._read_file(file)


if __name__ == '__main__':
    SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
    DATA_DIR = os.path.join(SCRIPT_DIR, 'data', 'JobPosting', 'ZhiLian')
    LOG_DIR = os.path.join(SCRIPT_DIR, 'logs')
    PROGRESS_DIR = os.path.join(SCRIPT_DIR, 'progress')
    SAVE_DIR = os.path.join(SCRIPT_DIR, 'data', 'JobPostDetail', 'ZhiLian')
    os.makedirs(SAVE_DIR, exist_ok=True)

    scraper = JobDetailScraper(LOG_DIR, PROGRESS_DIR)
    scraper.setup_logging()
    try:
        scraper.process_files()
    except Exception as e:
        scraper.log_error(f"Error: {str(e)}")
    finally:
        scraper.chrome.quit()
